apiVersion: apps/v1
kind: Deployment
metadata:
  name: charandemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charandemo
  template:
    metadata:
      labels:
        app: charandemo
    spec:
      containers:
      - name: charandemo
        image: us.icr.io/charandemo/charanapp:1