# apiVersion: v1
# kind: Service
# metadata:
#   name: charandemo-deployment
#   labels:
#     app: charandemo
# spec:
#   type: NodePort
#   selector:
#     app: charandemo
#   ports:
#   - protocol: TCP
#     port: 9417


apiVersion: v1
kind: Service
metadata:
  name: charandemo-deployment
  labels:
    app: charandemo
spec:
  selector:
    app: charandemo
  type: NodePort
  ports:
   - port: 9417
     nodePort: 31514